
export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"


export const LOGOUT_START = "LOGOUT_START"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILED = "LOGOUT_FAILED"


export const GET_COUNTS_START = "GET_COUNTS_START"
export const GET_COUNTS_SUCCESS = "GET_COUNTS_SUCCESS"
export const GET_COUNTS_FAILED = "GET_COUNTS_FAILED"


export const GET_CHART_DATA_START = "GET_CHART_DATA_START"
export const GET_CHART_DATA_SUCCESS = "GET_CHART_DATA_SUCCESS"
export const GET_CHART_DATA_FAILED = "GET_CHART_DATA_FAILED"



export const GET_POST_START = "GET_POST_START"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILED = "GET_POST_FAILED"


export const GET_USERS_START = "GET_USERS_START"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILED = "GET_USERS_FAILED"

export const REQUEST_CANCELLED = "REQUEST_CANCELLED"
export const LOCALSTORAGE_USER = 'LOCALSTORAGE_USER'



